name = "Haiti Presidents"
license = "MIT"
licenselink = "https://github.com/yourname/haiti-presidents/blob/master/LICENSE.md"
description = ""
homepage = "http://haitipresidents.com/"
tags = ["haiti", "presidents", "political", "people", "prezidan"]
features = ["people", "blog"]
min_version = 0.18

[author]
  name = "Kenold Beauplan"
  homepage = "https://www.twitter.com/kenoldb"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
